export const SET_ACTIVE_UNIT = "SET_ACTIVE_UNIT";

export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";

export const FETCH_ALERTS_REQUEST = "FETCH_ALERTS_REQUEST";
export const FETCH_ALERTS_SUCCESS = "FETCH_ALERTS_SUCCESS";
export const FETCH_ALERTS_FAILURE = "FETCH_ALERTS_FAILURE";

export const SET_THRESHOLD_REQUEST = "SET_THRESHOLD_REQUEST";
export const SET_THRESHOLD_SUCCESS = "SET_THRESHOLD_SUCCESS";
export const SET_THRESHOLD_FAILURE = "SET_THRESHOLD_FAILURE";