export const SET_ACTIVE_UNIT = "SET_ACTIVE_UNIT";
export const FETCH_WEATHER_FROM_BACKEND_REQUEST =
  "FETCH_WEATHER_FROM_BACKEND_REQUEST";
export const FETCH_WEATHER_FROM_BACKEND_SUCCESS =
  "FETCH_WEATHER_FROM_BACKEND_SUCCESS";
export const FETCH_WEATHER_FROM_BACKEND_ERROR =
  "FETCH_WEATHER_FROM_BACKEND_ERROR";
export const FETCH_WEATHER_DIRECTLY_REQUEST = "FETCH_WEATHER_DIRECTLY_REQUEST";
export const FETCH_WEATHER_DIRECTLY_SUCCESS = "FETCH_WEATHER_DIRECTLY_SUCCESS";
export const FETCH_WEATHER_DIRECTLY_ERROR = "FETCH_WEATHER_DIRECTLY_ERROR";
export const FETCH_ALERTS_REQUEST = "FETCH_ALERTS_REQUEST";
export const FETCH_ALERTS_SUCCESS = "FETCH_ALERTS_SUCCESS";
export const FETCH_ALERTS_FAILURE = "FETCH_ALERTS_FAILURE";
export const SET_THRESHOLD_REQUEST = "SET_THRESHOLD_REQUEST";
export const SET_THRESHOLD_SUCCESS = "SET_THRESHOLD_SUCCESS";
export const SET_THRESHOLD_FAILURE = "SET_THRESHOLD_FAILURE";